### ISSUE TITLE
error

### ISSUE THREAD

**Issue by veeramarni** [lqs469/easy-docker#1]
I wanted to try this but this fails

```
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (127)
    at Bus.emit (events.js:163:17)
    at ChildProcess.<anonymous> (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/examples/easy-docker/node_modules/nodemon/lib/monitor/run.js:118:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by lqs469** [comment]
@veeramarni, Thank you try it! This is error I think you can try `npm install --save-dev babel-cli`, And try `babel-node` in terminal to check if it work correctly. And I have put this dependence in `package.json`, You can delete node_modules and `npm install`. If it still doesn't work, What's your node version? maybe update node? If it still can't run or happen any question, Please tell me. thanks.
